// Employee permission names. These are the ONLY valid values that can be
// assigned to an employee's `permissions` array. Admin bypasses all checks.
export const PERMISSIONS = {
  EMPLOYEE_DASHBOARD_VIEW: 'EMPLOYEE_DASHBOARD_VIEW',
  USER_VERIFICATION_VIEW: 'USER_VERIFICATION_VIEW',
  USER_VERIFICATION_RECOMMEND: 'USER_VERIFICATION_RECOMMEND',
  USER_VERIFICATION_CORRECTION_REQUEST: 'USER_VERIFICATION_CORRECTION_REQUEST',
  PROPERTY_MODERATION_VIEW: 'PROPERTY_MODERATION_VIEW',
  PROPERTY_MODERATION_RECOMMEND: 'PROPERTY_MODERATION_RECOMMEND',
  PROPERTY_MODERATION_CORRECTION_REQUEST: 'PROPERTY_MODERATION_CORRECTION_REQUEST',
  ENQUIRY_VIEW: 'ENQUIRY_VIEW',
  ENQUIRY_UPDATE: 'ENQUIRY_UPDATE',
  CALL_NOTES_MANAGE: 'CALL_NOTES_MANAGE',
  VISIT_VIEW: 'VISIT_VIEW',
  VISIT_UPDATE: 'VISIT_UPDATE',
  FOLLOWUP_VIEW: 'FOLLOWUP_VIEW',
  FOLLOWUP_MANAGE: 'FOLLOWUP_MANAGE',
  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',
  INTERNAL_NOTES_VIEW: 'INTERNAL_NOTES_VIEW',
  INTERNAL_NOTES_MANAGE: 'INTERNAL_NOTES_MANAGE',
  REPORTS_VIEW: 'REPORTS_VIEW',
  VIEW_UNASSIGNED_RECORDS: 'VIEW_UNASSIGNED_RECORDS',
  EMPLOYEE_MANAGE: 'EMPLOYEE_MANAGE',
  ADMIN_SETTINGS_VIEW: 'ADMIN_SETTINGS_VIEW', // admin-only, never assignable to employees

  // Manager permissions — one per grantable tab. Only these may be assigned to
  // a manager's `permissions` array via the admin Managers screen.
  MANAGER_PROPERTIES_VIEW: 'MANAGER_PROPERTIES_VIEW',
  MANAGER_ENQUIRIES_VIEW: 'MANAGER_ENQUIRIES_VIEW',
  MANAGER_CATEGORIES_VIEW: 'MANAGER_CATEGORIES_VIEW',
  MANAGER_MEDIA_RULES_VIEW: 'MANAGER_MEDIA_RULES_VIEW',
  MANAGER_CMS_VIEW: 'MANAGER_CMS_VIEW',
  MANAGER_LOCATIONS_VIEW: 'MANAGER_LOCATIONS_VIEW',
  MANAGER_PROPERTY_FIELDS_VIEW: 'MANAGER_PROPERTY_FIELDS_VIEW',
  MANAGER_REGISTRATION_FORMS_VIEW: 'MANAGER_REGISTRATION_FORMS_VIEW',
  MANAGER_SETTINGS_VIEW: 'MANAGER_SETTINGS_VIEW',
};

// Permissions that can be assigned to an employee via the employee management screen.
export const ASSIGNABLE_EMPLOYEE_PERMISSIONS = Object.values(PERMISSIONS).filter(
  (p) => p !== PERMISSIONS.ADMIN_SETTINGS_VIEW
);

// Permissions that can be assigned to a manager via the admin Managers screen.
export const ASSIGNABLE_MANAGER_PERMISSIONS = [
  PERMISSIONS.MANAGER_PROPERTIES_VIEW,
  PERMISSIONS.MANAGER_ENQUIRIES_VIEW,
  PERMISSIONS.MANAGER_CATEGORIES_VIEW,
  PERMISSIONS.MANAGER_MEDIA_RULES_VIEW,
  PERMISSIONS.MANAGER_CMS_VIEW,
  PERMISSIONS.MANAGER_LOCATIONS_VIEW,
  PERMISSIONS.MANAGER_PROPERTY_FIELDS_VIEW,
  PERMISSIONS.MANAGER_REGISTRATION_FORMS_VIEW,
  PERMISSIONS.MANAGER_SETTINGS_VIEW,
];
